<a href="https://colab.research.google.com/github/areebaarshadqureshi/Data-Science-Journey-CampusX/blob/main/02-Numpy/01-Numpy-Fundamentals/Numpy_Fundamentals_Notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [ ]:
#np.array
import numpy as np
a=np.array([1,2,3]) #1D=====vector
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
#2D and 3D

b= np.array([[1,2,3],[4,5,6]])
print(b) #2D=======matrix
print()
c=np.array([[[1,2,3],[5,6,7],[7,8,9]]])
print(c)#3D========tensor

[[1 2 3]
 [4 5 6]]

[[[1 2 3]
  [5 6 7]
  [7 8 9]]]


In [ ]:
#dtype
a=np.array([1,2,3],dtype=float)
print(a)

b=np.array([1,2,3],dtype=complex)
print(b)

[1. 2. 3.]
[1.+0.j 2.+0.j 3.+0.j]


In [ ]:
#np.arange-------------------working like range
#print numpy array form 1-10
a=np.arange(1,11)
print(a)
b=np.arange(2,21,2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
#with reshape----------------change given shape into your choice shape
a=np.arange(1,11)
print(a)

b=a.reshape(2,5) #rows--2 and columns----5

print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
#np.ones and np.zeros
np.ones((3,4)) #provide tuple shape and it create numpy array with value one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

#ones,zeros ,random nmupy are used to initialize values

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#np.random
np.random.random((3,4)) #generate numbers between 0 and 1

array([[0.59870333, 0.46875111, 0.53804421, 0.75824306],
       [0.26699269, 0.87335706, 0.01865811, 0.59878073],
       [0.44728388, 0.32679082, 0.63316559, 0.7417453 ]])

In [ ]:
#np.linspace-----------------lineraly space
np.linspace(-10,10,12) #12 numbers between -10 and 10
#used in ML

array([-10.        ,  -8.18181818,  -6.36363636,  -4.54545455,
        -2.72727273,  -0.90909091,   0.90909091,   2.72727273,
         4.54545455,   6.36363636,   8.18181818,  10.        ])

In [ ]:
#np.identity
a=np.identity(3) #3x3 matirx
#daigonals ---1 and remaining -----------zeros
print(a)
print()
b=np.identity(3,dtype=int)
print(b)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1 0 0]
 [0 1 0]
 [0 0 1]]


### Array Attributes

In [ ]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
#ndim----no of dimension
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)
#(2,2,2) -----(how many 2d arrays,rows,columns)

1
2
3


In [ ]:
#shape----------------rows and columns
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [ ]:
#size----------------no of items
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [ ]:
#itemsize---------------how much memory occupied by each item
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)


4
8
8


In [ ]:
#type----------------------dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


### Changing Datatype

In [ ]:
#astype
import numpy as np
a3=np.arange(10)
print(a3)
a3.astype(np.int32)

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

### Array Operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
#sacalar operation

#1.airthematic
a1*2

#all operations /,**,*,%

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [ ]:
#2.reltional
a2>16 #----it compare each item by 16

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
#Vector operation
#1.airthematic
a1+a2 #shape should be same
#all operation work
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

### Array Functions

In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[16., 55., 74.],
       [ 5., 81.,  2.],
       [96., 38., 36.]])

In [ ]:
# max/min/sum/prod

print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

#find out each row minimum number
# 0 -> col and 1 -> row
print(np.min(a1,axis=1))



96.0
2.0
403.0
6927184281600.0
[16.  2. 36.]


In [ ]:
# mean/median/std/var
print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))
print(np.var(a1))

44.77777777777778
38.0
32.0720639178494
1028.617283950617


In [ ]:
# trignomoetric function
print(np.sin(a1))
print(np.cos(a1))
print(np.tan(a1))

[[-0.28790332 -0.99975517 -0.98514626]
 [-0.95892427 -0.62988799  0.90929743]
 [ 0.98358775  0.29636858 -0.99177885]]
[[-0.95765948  0.02212676  0.17171734]
 [ 0.28366219  0.77668598 -0.41614684]
 [-0.18043045  0.95507364 -0.12796369]]
[[  0.30063224 -45.18308791  -5.73702254]
 [ -3.38051501  -0.81099442  -2.18503986]
 [ -5.45134011   0.31030966   7.75047091]]


In [ ]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

print(a2)
print()
print(a3)
print()
print(np.dot(a2,a3))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]

[[114 120 126]
 [378 400 422]
 [642 680 718]]


In [ ]:
# log and exponents
print(np.log(a1))
print()
print(np.exp(a1))

[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


/tmp/ipython-input-31-1420843470.py:2: RuntimeWarning: divide by zero encountered in log
  print(np.log(a1))


In [ ]:
# round/floor/ceil
print(np.round(np.random.random((2,3))*100,2))
print(np.floor(np.random.random((2,3))*100))
print(np.ceil(np.random.random((2,3))*100))

[[88.32 52.27 63.07]
 [57.66 88.14 98.29]]
[[19. 80. 26.]
 [35. 72. 57.]]
[[28. 13. 57.]
 [80.  9.  4.]]


### Indexing and Slicing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
#find out last element
print(a1[-1])
#findout first element
print(a1[0])
#find out 3rd element
print(a1[2])

9
0
2


In [ ]:
#find elements on 2D array
print(a2)
print()
print(a2[1,2])#[row,col]
print(a2[2,-1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

6
11


In [ ]:
#find out values from 3D
a3 = np.arange(8).reshape(2,2,2)
print(a3)
print()
print(a3[1,0,1]) ##[2dblock number,row,col]
print(a3[0,1,0])
print(a3[0,0,0])
print(a3[1,1,-1])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

5
2
0
7


In [ ]:
##fetch multiple items
print(a1[2:5])
#in 2d
print(a2)
print()
##first row and all column
print(a2[0,:]) #[row,column]

##all row and 2 column
print(a2[:,2])

#fetch 5,6,9,10
print(a2[1:,1:3])
print()
print(a2[::2,::3])
print()
print(a2[::2,1::2])
print()
print(a2[1,::3])
print()
print(a2[0:2,1:])

[2 3 4]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[0 1 2 3]
[ 2  6 10]
[[ 5  6]
 [ 9 10]]

[[ 0  3]
 [ 8 11]]

[[ 1  3]
 [ 9 11]]

[4 7]

[[1 2 3]
 [5 6 7]]


In [ ]:
#In 3D
a3=np.arange(27).reshape(3,3,3)
print(a3)
print()

print(a3[1,:,:]) #[block number,row,col]
print()
print(a3[::2,:,:])
print()
print(a3[0,1,:])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

[3 4 5]


In [ ]:
#
print(a3[1,:,1])
print()
print(a3[2,1:,1:])
print()
print(a3[::2,0,::2])
print()

[10 13 16]

[[22 23]
 [25 26]]

[[ 0  2]
 [18 20]]


### Iterating


In [ ]:
a1

for i in a1:
  print(i)


0
1
2
3
4
5
6
7
8
9


In [ ]:
a2
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
a3
for i in a3:
    print(i)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
#looping on individual items
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [ ]:
# reshape

In [ ]:
# Transpose
print(np.transpose(a2))
#or
print(a2.T)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
#ravel-------------convert n dimension array into 1 D
a2
print(a2.ravel())


[ 0  1  2  3  4  5  6  7  8  9 10 11]


### Stacking

In [ ]:
# horizontal stacking--------------join 2 numpy array
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

#a1=2X2,a2=2X2 --------HS=2x4--------------VS=4x2
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
#vertical stacking
np.vstack((a4,a5))

##where we use
##stacking multiple sources data,API,Database,----

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [ ]:
# horizontal splitting-------------split the matrix
print(a4)
a6,a7 = np.hsplit(a4,2) #[nparray,split in __parts]
print(a6)
print()
print(a7)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1]
 [4 5]
 [8 9]]

[[ 2  3]
 [ 6  7]
 [10 11]]


In [ ]:
#vertical split
print(a4)
np.vsplit(a4,3)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [ ]:
np.vsplit(a4,2) ##we cannot split it into 2 parts because it doesnot contain equal division

ValueError: array split does not result in an equal division