<a href="https://colab.research.google.com/github/areebaarshadqureshi/Data-Science-Journey-CampusX/blob/main/02-Numpy/01-Numpy-Fundamentals/Numpy_Fundamentals_Tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [ ]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [ ]:
a1=np.zeros(10)
a1[4]=1
print(a1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [ ]:
a,b=map(int,input("Enter any two numbers seperated by comma:").split(","))
print(np.random.random((a,b)))

Enter any two numbers seperated by comma:2,3
[[0.67619473 0.25604836 0.88131447]
 [0.55875779 0.83922386 0.26946901]]


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [ ]:
def func(a,b):
    a1=np.zeros((a,b))
    for i in range(a):
        for j in range(b):
            if i==0 or i==a-1 or j==0 or j==b-1:
              a1[i][j]=1
    return a1


a=int(input("Enter no of row:"))
b=int(input("Enter no of  columns:"))
func(a,b)

Enter no of row:4
Enter no of  columns:4


array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [ ]:
a1=np.linspace(0,1,12)
a1=a1[1:11]
print(a1)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
# No, you cannot create a true identity matrix of shape (3, 4), because an identity matrix must be square — i.e., same number of rows and columns (like 3×3, 4×4, etc.).

a1=np.zeros((3,4))
for i in range(3):
    for j in range(4):
        if i==j:
          a1[i][j]=1

print(a1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [ ]:
a1=np.zeros((5,5))
for i in range(5):
  for j in range(5):
    a1[i][j]=np.random.randint(0,5)
print(a1)

[[3. 4. 1. 1. 3.]
 [4. 3. 4. 1. 2.]
 [2. 3. 2. 3. 0.]
 [3. 3. 4. 0. 4.]
 [4. 4. 3. 3. 3.]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [ ]:
point = np.array([2,3])
vect=np.random.randint(1,101,size=(10,2))
#print(vect)
dist=np.zeros(10,dtype=int)
for i in range(10):
    d=np.sqrt((point[0]-vect[i][0])**2+(point[1]-vect[i][1])**2)
    dist[i]=d
print(dist)


[ 91  80  55  93  61 100  61  90  24  80]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
a1=np.random.random((6,7,8))
#print(a1)
index=np.unravel_index(99,a1.shape)
print(a1[index])

0.2149611803205005


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [ ]:
import numpy as np
num=map(int,input("Enter any numbers seperated by space:").split(" "))
np_array=np.array(list(num),dtype=float)
print(np_array[::-1])

Enter any numbers seperated by space:1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [ ]:
np_array=np.array([1,2,3,4,5,0])
print(np_array.size)

6


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [ ]:
s_array=np.array([33.17344305 ,45.61961654, 82.05405781, 80.9647098,  68.82830233, 91.52064278])
exp_values = np.exp(s_array - np.max(s_array))
softmax_output = exp_values / np.sum(exp_values)

print(softmax_output)

[4.57181033e-26 1.16249922e-20 7.73872594e-05 2.60358426e-05
 1.39571531e-10 9.99896577e-01]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [ ]:
a=np.array([[0, 1, 2, 3, 4],
 [5, 6, 7, 8, 9]])
b=np.array( [[1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1]] )
c=np.array([[0.10117373, 0.1677244,  0.73764059, 0.83166097, 0.48985695],
 [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]])
print(np.vstack((a,b,c)))

[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
def func(arr):
  s=np.datetime64(arr[0])
  e=np.datetime64(arr[1])
  return np.arange(s,e)



date_array=np.array(['2020-11-25','2020-11-30'])
func(date_array)

array(['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
       '2020-11-29'], dtype='datetime64[D]')

###`Q-14:` Subtract the mean of each row from a matrix.

In [ ]:
arr=np.random.random((3,3)).round(1)*100
print(arr)
print()
m=np.mean(arr,axis=1).round(2)
output=arr-m
print(output)

[[ 10. 100.  30.]
 [ 40.  30.  40.]
 [ 50.  90.  20.]]

[[-36.67  63.33 -23.33]
 [ -6.67  -6.67 -13.33]
 [  3.33  53.33 -33.33]]


###`Q-15:` Swap column-1 of array with column-2 in the array.

In [ ]:
arr=np.random.random((3,3)).round(1)*100
print(arr)
arr[:,[0,1]]=arr[:,[1,0]]

print(arr)

[[90.  0. 60.]
 [60. 20. 20.]
 [10. 60. 20.]]
[[ 0. 90. 60.]
 [20. 60. 20.]
 [60. 10. 20.]]


###`Q-16:` Replace odd elements in arrays with -1.

In [ ]:
arr=np.random.random((3,3)).round(2)*100
print(arr)

arr[arr%2!=0]=-1
print(arr)

[[52.  9. 50.]
 [85. 91. 58.]
 [94. 29. 74.]]
[[52. -1. 50.]
 [-1. -1. -1.]
 [94. -1. 74.]]


###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [ ]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
print(a,b)
result=np.array([])
for i in range(len(a)):
  if a[i]<b[i]:
    result=np.append(result,b[i])
  else:
    result=np.append(result,a[i])
result=result.astype(np.int64)
print(result)

[6 3 1 5 8] [3 2 1 7 2]
[6 3 1 7 8]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [ ]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[5631, 9626, 8646, 7685, 4808],
       [8407, 3306, 9612, 3714,  258],
       [5133, 4935, 2046, 5007, 6903],
       [6988, 9872, 2315,  866, 4115],
       [1564, 1894, 6186, 8229, 5626],
       [4213, 5492, 9966, 6866, 4027],
       [4159, 1823, 3965, 7042, 3428],
       [7099, 7538, 2577,  427, 7859]])

In [ ]:
X_norm=arr-np.min(arr)/np.max(arr)-np.min(arr)
print(X_norm)

[[5.30106383e+01 1.06382979e-02 5.10106383e+01]
 [1.06382979e-02 1.06382979e-02 1.06382979e-02]
 [9.50106383e+01 1.06382979e-02 7.50106383e+01]]


###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [ ]:
def func(arr,n):
   arr=np.sort(arr)
   return arr[-n]

arr=np.array([12,34,40,7,1,0])
n=4
if n<=len(arr):
  ans=func(arr,n)
  print(ans)
else:
  print("Not in array length")


7


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [ ]:
a = np.array([1,2,3])
b=np.repeat(a,len(a))
c=np.tile(a,len(a))
b=np.concatenate((b,c))
print(b)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
