<a href="https://colab.research.google.com/github/areebaarshadqureshi/Data-Science-Journey-CampusX/blob/main/02-Numpy/03-Numpy-Tricks/Numpy_Tricks_Tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [ ]:
import numpy as np
arr=np.random.randint(0,100,(3,4))
print(arr)
print()
#i
print(np.sort(arr))
#ii
print()
print(arr[arr[:,1:].argsort()])
#iii
print()
print(arr[arr.max(axis=1).argsort()])
print()
#iv
print(np.sort(arr,axis=None).reshape(4,3))

[[60 27 20 42]
 [53 78 76 72]
 [88 73 20 92]]

[[20 27 42 60]
 [53 72 76 78]
 [20 73 88 92]]

[[[53 78 76 72]
  [60 27 20 42]
  [88 73 20 92]]

 [[88 73 20 92]
  [53 78 76 72]
  [60 27 20 42]]

 [[53 78 76 72]
  [60 27 20 42]
  [88 73 20 92]]]

[[60 27 20 42]
 [53 78 76 72]
 [88 73 20 92]]

[[20 20 27]
 [42 53 60]
 [72 73 76]
 [78 88 92]]


###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [ ]:
marks =np.array( [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])
extra_subject = np.array([41, 87, 72, 36, 92]).reshape(5,1)
# Two extra students record-
rec1 = np.array([77, 83, 98, 95, 89]).reshape(1,5)
rec2 = np.array([92, 71, 52, 61, 53]).reshape(1,5)

#i
marks=np.concatenate((marks,extra_subject),axis=1)
print(marks)
#ii
new_record=np.concatenate((rec1,rec2),axis=0)

print()
n=np.concatenate((marks,new_record),axis=0)
print(n)

#iii
extra=np.sum(n,axis=1).reshape(-1,1)
print()
print(extra)
#iv
final=np.concatenate((n,extra),axis=1)
print()
print(final)

#iv
print(final[final[:,-1].argsort()])

[[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]]

[[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]
 [77 83 98 95 89]
 [92 71 52 61 53]]

[[106]
 [328]
 [229]
 [234]
 [315]
 [442]
 [329]]

[[ 13  10   9  33  41 106]
 [ 63  46  90  42  87 328]
 [ 39  76  13  29  72 229]
 [ 82   9  29  78  36 234]
 [ 67  61  59  36  92 315]
 [ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]
[[ 13  10   9  33  41 106]
 [ 39  76  13  29  72 229]
 [ 82   9  29  78  36 234]
 [ 67  61  59  36  92 315]
 [ 63  46  90  42  87 328]
 [ 92  71  52  61  53 329]
 [ 77  83  98  95  89 442]]


###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [ ]:
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

print(np.unique(arr,axis=0))
print(np.unique(arr,axis=1))


[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]


###`Q-4:` Flip given 2-D array along both axes at the same time.

In [ ]:
np.flip(arr,axis=(0,1))

array([[1, 1, 3, 3, 2, 1],
       [8, 8, 8, 3, 2, 1],
       [8, 8, 2, 1, 9, 0],
       [1, 1, 3, 3, 2, 1]])

### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [ ]:
arr = np.array([[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]])
X=6
rows,col=np.where(arr>X)
print(np.unique(rows))


[1 3]


### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [ ]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [ ]:
np.ravel(np.concatenate((arr1,arr2,arr3)))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [ ]:
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))

print()
print(np.delete(arr,np.where(arr==np.max(arr))))
print()
print(np.delete(arr,np.where(arr==np.min(arr))))


[563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882 181
 425 790 635 889 818 872 967 277 470 336 920 917 295 557 830 506 385 353
 975 592 997 137 340 222 215 472 459 617 649 935 956 914 932 645 952 921
 490 527 972 278 307 840 958 246 449 251 957 103 627 920 824 356 825 173
 323 372 960 710 464 244 782 763 635 436 774 171 469 178 458 624 211 771
 270 308 231 952 514 699 702 433 900 373 318 265 503 320 230 324 922 967
 620 743 527 117 566 804 123 946 587 227 853 757 944 328 855 930 325 729
 426 514 296 879 575 936 705 209 191 743 510 513 628 559 658 528 395 525
 922 136 496 225 895 975 263 908 420 711 800 976 786 235 930 859 618 226
 695 460 218 483 490 803 621 453 193 607 677 637 728 724 534 748 291 194
 761 875 687 569 228 482 781 554 654 739 885 197 266 228 892 207 883 588]

[563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882 181
 425 790 635 889 818 872 967 277 470 336 920 917 295 557 830 506 385 353
 975 592 997 137 340 222 215 472 459 617 649 935

### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [ ]:
arr=np.random.randint(100,700,100)
print(arr)
print()
c=np.clip(arr,100,200)
print(c)
print()
s=np.sort(c)
print(s)
print()
print(np.cumsum(s))


[553 258 664 398 203 491 103 401 213 130 284 236 681 284 258 138 437 303
 226 407 498 446 604 187 175 332 627 466 228 546 140 128 385 259 672 344
 503 608 123 438 582 678 338 292 185 458 198 421 584 361 334 467 435 330
 381 329 618 336 186 109 288 636 381 644 573 169 402 465 693 571 460 465
 608 684 546 553 698 453 643 396 626 112 198 655 401 385 175 425 597 469
 580 400 406 355 259 502 572 471 103 604]

[200 200 200 200 200 200 103 200 200 130 200 200 200 200 200 138 200 200
 200 200 200 200 200 187 175 200 200 200 200 200 140 128 200 200 200 200
 200 200 123 200 200 200 200 200 185 200 198 200 200 200 200 200 200 200
 200 200 200 200 186 109 200 200 200 200 200 169 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 112 198 200 200 200 175 200 200 200
 200 200 200 200 200 200 200 200 103 200]

[103 103 109 112 123 128 130 138 140 169 175 175 185 186 187 198 198 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 2

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [ ]:
arr=np.random.random((3,4)).round(3)
print(arr)
print()
print(np.percentile(arr,0))
print()
print(np.percentile(arr,100))
print()
print(np.percentile(arr,51)-np.percentile(arr,50))

[[0.977 0.456 0.195 0.488]
 [0.828 0.861 0.655 0.182]
 [0.613 0.676 0.041 0.334]]

0.041

0.977

0.01375000000000004
